version: '3.8'

services:
  schedule-api:
    build: 
      context: ./schedule-api
      dockerfile: Dockerfile
    container_name: schedule-api
    ports:
      - "9020:9020"
    environment:
      - NODE_ENV=production
      - PORT=9020
      - JWT_SECRET=schedule-jwt-secret-production
      - CORS_ORIGIN=http://localhost:8080
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped

  schedule-ui:
    build:
      context: ./schedule-ui
      dockerfile: Dockerfile
    container_name: schedule-ui
    ports:
      - "8080:80"
    depends_on:
      - schedule-api
    restart: unless-stopped

volumes:
  data:
  logs: